#!/usr/bin/python

import os
import shutil
import sys
import argparse

if __name__ == "__main__":

    parser = argparse.ArgumentParser(
          description="Tool to rename a set of BDT xml files.",
          formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    
    parser.add_argument("pattern", metavar="PATTERN", 
          help="Pattern of the new BDT using {c} and {s} for category and set.")
      
    args = parser.parse_args() 

    script_dir = os.path.dirname(os.path.realpath(__file__))
    os.chdir(os.path.join(script_dir, "../weights"))

    sources =  [
        "run2_test_BDT_Even_VBF.weights.xml",
        "run2_test_BDT_Odd_VBF.weights.xml",
        "run2_test_BDT_Even_Boosted.weights.xml",
        "run2_test_BDT_Odd_Boosted.weights.xml",
    ]

    targets = []
    for cat in ("VBF", "Boosted"):
        for set in ("Even", "Odd"):
            targets.append(args.pattern.format(c=cat, s=set))

    for source, target in zip(sources, targets):
        print("%s -> %s" % (source, target))
        shutil.copy(source, target)
