#!/bin/bash
shopt -s expand_aliases
sleep 510
cd /data/apathak/VF_ITK_30Oct2018_r10899
# directly go to directory to launch jobs so that multiple instances of asetup can be run simultaneously without interfereing with each other
export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/atlasLocalSetup.sh
asetup 20.20.12.3,AtlasProduction,here,slc6
cd /data/apathak/VF_ITK_30Oct2018_r10899/RunArea/Reconstr_18
rm -f reco.log
time ./reco.todo 2>&1 > reco.log
